### ISSUE TITLE
Shamsi date

### ISSUE THREAD

**Issue by aaazv** [runo280/ShamsiDate#1]
سلام، آقا دستت درد نکنه. میتونی برای نوتیفیکیشن یه ماژول درست کنی که تاریخ میلادی رو شمسی نشون بده؟

**Comment by aaazv** [comment]
Have a look to the Ayam ایام app.
Its a great app, but it didnt work on mm

**Comment by runo280** [comment]
سلام، دقیقا منظورتون کجاست؟
جایی که نویتیفیکیشن دراور رو می کشیم پایین یدونه تاریخ میلادی هست اونجا رو میگید؟

**Comment by aaazv** [comment]
بله دقیقا

 
 
  On Tue, Jan 15, 2019 at 7:08, Ruhollah<notifications@github.com> wrote:   
سلام، دقیقا منظورتون کجاست؟
جایی که نویتیفیکیشن دراور رو می کشیم پایین یدونه تاریخ میلادی هست اونجا رو میگید؟

**Comment by aaazv** [comment]
منتظر آپدیت بعدی با قابلیت مذکور باشم؟

**Comment by runo280** [comment]
بله بزودی

**Comment by Ali-Javadi** [comment]
Hi
I installed ShameiDate on Lineage 16 and EdXposed 0.9.2.8
But unfortunately it doesn't show in status bar and lockscreen.
Is that because of resources hooking or something else?
How can I send log to you?
Thank you

**Comment by runo280** [comment]
سلام
الان گوشی من و xposed از LOS16 پشتیبانی رسمی نمی کنن
خود LOS16 هم هنوز در حال توسعه هست هنوز
ولی شما میتونید داخل اپه Xposed Installer قسمت Logs میتونید یه لاگ ها رو
توی یه فایل ذخیره کنید و توی یه isssue جدید بزارید تا سر فرصت نگاه کنم.

**Comment by runo280** [comment]
> Hi
> I installed ShameiDate on Lineage 16 and EdXposed 0.9.2.8
> But unfortunately it doesn't show in status bar and lockscreen.
> Is that because of resources hooking or something else?
> How can I send log to you?
> Thank you

<div dir="rtl">
با این کامیت الان روی رام AOSiP تست کردم مشکلی نداره
</div>
[Compatibility with Pie](https://github.com/runo280/ShamsiDate/commit/8939aff604a41fb7171c29917fa536c883b94f83)

**Comment by aaazv** [comment]
سلام. نصب کردم.

فقط فونت ساعت گوشیم تغییر کرده، نه تاریخ استاتوس بار تغییر کرده و نه تو صفحه لاک اسکرین.

نوت7، اندروید 7

**Comment by aaazv** [comment]
![Screenshot_20190607-104559](https://user-images.githubusercontent.com/19729879/59084942-40239080-8912-11e9-8276-efc9a3a2ca5e.png)
![Screenshot_20190607-105111](https://user-images.githubusercontent.com/19729879/59084948-47e33500-8912-11e9-84d9-ea8981f7307a.png)

**Comment by aaazv** [comment]
![Screenshot_20190607-105256](https://user-images.githubusercontent.com/19729879/59085010-6cd7a800-8912-11e9-9d1b-c62fee518ba9.png)

**Comment by runo280** [comment]
همون طور که توی توضیحات نوشتم فقط احتمال داره روی نسخه های خام اندروید جواب بده
باقی رام ها به شدت دستکاری شدن و اگر سورسشون در دسترس بود خب میشد از اونام پشتیبانی کرد.

**Comment by runo280** [comment]
> 
> 
> سلام، آقا دستت درد نکنه. میتونی برای نوتیفیکیشن یه ماژول درست کنی که تاریخ میلادی رو شمسی نشون بده؟

اینم حل شد بزودی آپدیت میدم
