### ISSUE TITLE
Display date in ambient display (Android 9)

### ISSUE THREAD

**Issue by mu4um** [runo280/ShamsiDate#2]
سلام، امکانش هست موقعی که گوشی رو برمی داریم و صفحه روشن میشه تاریخ شمسی هم بیاد. منظور ambient display هست. ممنون
![XQgX2hHHPb](https://user-images.githubusercontent.com/34750114/55022504-4f37b980-5018-11e9-9d28-2e7888188878.png)

**Comment by runo280** [comment]
سلام، خودمم دوست داشتم این شکلی بشه، امروزم که یه تلاشی کردم ولی نشد

**Comment by runo280** [comment]
خب یه تلاش دیگه کردم و اینبار موفق شدم بزودی آپدیت میدم

**Comment by mu4um** [comment]
آقا دستت درد نکنه، فقط یه چیزی من وقتی آپدیت کردم به اندروید ۹ دیگه کلا رو لاک اسکرین تاریخ شمسی نشون نمیده. بقیه جاها 
 درسته اما لاک اسکرین نه. خواستم ببینم طبیعیه رو اندروید ۹ یا فقط مشکل منه؟

**Comment by runo280** [comment]
رام گوشیتون چی هست؟
من بر اساس سورس لایج ایج ساختمش که سورس این [کلاس ](https://raw.githubusercontent.com/LineageOS/android_frameworks_base/lineage-16.0/packages/SystemUI/src/com/android/systemui/statusbar/policy/DateView.java)تو نسخه 16 و 15.1 یکی هست
رام گوشیم هم الان رو نسخه 15.1 هست نشد دیگه روی 16 تست کنم

**Comment by mu4um** [comment]
AOSiP روی nexus 5x

**Comment by runo280** [comment]
توی سورس نسخه 15.1 این کلاسی که قبلا لینکش رو گزاشتم برای لاک اسکرین استفاده شده
ولی توی نسخه 16 اثری از استفاده این کلاس برای لاک اسکرین نیست
اگر هم تاریخ تو حالت عادی تاریخ هست هنوز نتونستم سردربیارم چه شکلی نشونش میدن
فکر کنم برای اندروید 9 باید مثل روش قبل عمل کنم فعلا

**Comment by runo280** [comment]
این نسخه رو تست کنید نتیجه رو به بگید
[ShamsiDate_v1.3.1.zip](https://github.com/runo280/ShamsiDate/files/3439426/ShamsiDate_v1.3.1.zip)

**Comment by mu4um** [comment]
این نسخه کلا هیج تغییری ایجاد نمی کنه. همه چیز مثل حالت عادی گوشی شده.

**Comment by runo280** [comment]
تا زمانی که باگ مربوط به گوشیم و قابل استفاده شدن
xposed
روی اندروید پای حل نشه کار زیادی از دستم برنمیاد

**Comment by runo280** [comment]
این روی رام شما تست شد
فقط فونت لاک اسکرین تاریخ هنوز مونده
[ShamsiDate_v1.3.2.zip](https://github.com/runo280/ShamsiDate/files/3455102/ShamsiDate_v1.3.2.zip)

**Comment by runo280** [comment]
اگر تغییراتی ندیدید دوباره ریبوت کنید
یا یبار حذف و دوباره نصب کنید
برای منم چندین بار کارنکرد
فکر کنم بیشتر به Xposed مربوطه که هنوز پایدار نشده
چون خطایی تو لاگ های ماژول دیده نمیشه

**Comment by mu4um** [comment]
خیلی ممنون، درست شد.
