### ISSUE TITLE
Please support Lineage 17 (Android 10)

### ISSUE THREAD

**Issue by hamedsbt** [runo280/ShamsiDate#3]
Please support Lineage 17 (Android 10)

**Comment by runo280** [comment]
I will do it as soon as possible.

**Comment by runo280** [comment]
دسترسی ندرام به نسخه 17 ولی میتونید اینو تست کنید نتیجه رو به من بگید
[ShamsiDate_v3.0.zip](https://github.com/runo280/ShamsiDate/files/4036337/ShamsiDate_v3.0.zip)

**Comment by hamedsbt** [comment]
سلام و سپاسگذارم...
متاسفانه کار نکرد. رام گوشی 
https://github.com/ender1324/baconOTA
هست. همچنین تاپیک رام:
https://forum.xda-developers.com/oneplus-one/development/rom-lineageos-oneplus-one-t4002111/post81395061#post81395061

**Comment by hamedsbt** [comment]
اگر مایلید نسخه بدین که لاگ plain text بزنه... میتونم براتون ارسال کنم

**Comment by runo280** [comment]
<div dir="rtl">

فکر کنم لاگ Xposed Manager هم کمک کنه

احتمال زیاد خطایی رخ داده که اونجا قابل مشاهده هست

اگر تونستید نگاهی بکنید و اگر چیزی بود بفرستید

غیر این بود سعی میکنم نسخه ای که گفتین رو آماده کنم
</div>

**Comment by runo280** [comment]
<div dir="rtl">
ایراد از من بود

این باید کار کنه
</div>
<a href="https://github.com/runo280/ShamsiDate/files/4049121/ShamsiDate_v3.0.zip">ShamsiDate_v3.0.zip</a>

**Comment by hamedsbt** [comment]
ممنون، کار کرد.
