### ISSUE TITLE
مشکل در شیاومی ردمی نوت ۷ پرو ، اندروید ۹

### ISSUE THREAD

**Issue by pouyahz** [runo280/ShamsiDate#5]
سلام
هیچ تغییری ایجاد نمیشه 
تاریخ جایی نشون نمیده

**Comment by pouyahz** [comment]
miui 11

**Comment by runo280** [comment]
سلام
در توضیحات هم نوشتم **فقط احتمال داره روی نسخه های خام اندروید کار کنه**
